name: Build and Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          # for the deployment to work correctly
          persist-credentials: false

      - name: Install
        uses: bahmutov/npm-install@v1

      - name: Build ğŸ”§
        run: |
          mkdir website
          yarn typedoc
          sed 's% src="/_src_/index.js"% src="https://cdn.skypack.dev/twind"%g;s% src="/_src_/shim/index.js"% src="https://cdn.skypack.dev/twind/shim"%g' < example/landing.html > website/index.html

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: main
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: website # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          CLEAN_EXCLUDE: '["CNAME", ".nojekyll"]'
