name: Build and Deploy Website

on:
  push:
    branches:
      - v0.16

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2
        with:
          # for the deployment to work correctly
          persist-credentials: false

      - name: Install
        uses: bahmutov/npm-install@v1
        with:
          working-directory: |
            .
            docs

      - name: Build üîß
        run: |
          cd docs
          yarn build

      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: v0.16
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/.vitepress/dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          CLEAN_EXCLUDE: '["CNAME", ".nojekyll"]'
